---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: patroni
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patroni
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patroni