apiVersion: v2
name: pidp
description: A master helm chart for Kubernetes deployment of the PIDP application.
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://svgshare.com/i/_6C.svg
dependencies:
  - name: frontend
    repository: "file://../frontend"
    version: "0.1.1"
  - name: webapi
    repository: "file://../webapi"
    version: "0.1.5"
  - name: plr-intake
    repository: "file://../plr-intake"
    version: "0.1.2"
  - name: nginx
    repository: "file://../nginx"
    version: "9.8.0"
  # - name: trivy
  #   repository: "https://aquasecurity.github.io/helm-charts/"
  #   version: "0.26.0"
  #   condition: trivy.enabled