cron: 0 8 * * *

global:
  vanityURL: "healthprovideridentityportal.gov.bc.ca"
  commit_sha: ""
  image:
    registry: image-registry.openshift-image-registry.svc:5000/d8a8f9-tools
    repository: endorsement-reminder
    # Overrides the image tag whose default is the chart appVersion.
    tag: develop
imagePullSecrets: []
image:
  pullPolicy: Always
  
aspnetcore:
  environment: Staging
env: dev

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi