---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: database
  app.kubernetes.io/instance: ${INSTANCE}
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: patroni
  app.kubernetes.io/version: "12"
  cluster-name: ${INSTANCE}
metadata:
  annotations:
    description: Patroni Postgresql database cluster secret generator
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql
    openshift.io/long-description: This template creates a patroni postgresql secret.
    tags: postgresql
  name: patroni-pgsql-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-${INSTANCE}-secret
  stringData:
    app-db-name: ${APP_DB_NAME}
    app-db-password: ${APP_DB_PASSWORD}
    app-db-username: ${APP_DB_USERNAME}
    replication-password: ${PATRONI_REPLICATION_PASSWORD}
    replication-username: ${PATRONI_REPLICATION_USERNAME}
    superuser-password: ${PATRONI_SUPERUSER_PASSWORD}
    superuser-username: ${PATRONI_SUPERUSER_USERNAME}
parameters:
- description: The name of the application for labelling all artifacts.
  displayName: Application Name
  name: NAME
  required: true
  value: patroni
- description: The name of this instance of the application
  displayName: Application Instance Name
  name: INSTANCE
  required: true
- description: Name of the application database
  displayName: Application Database Name
  name: APP_DB_NAME
  required: true
  value: app
- description: Username of the application database
  displayName: Application Database Username
  name: APP_DB_USERNAME
  required: true
  value: app
- description: Password of the application database
  displayName: Application Database Password
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: APP_DB_PASSWORD
  required: true
- description: Username of the superuser account for initialization.
  displayName: Superuser Username
  name: PATRONI_SUPERUSER_USERNAME
  required: true
  value: postgres
- description: Password of the superuser account for initialization.
  displayName: Superuser Passsword
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: PATRONI_SUPERUSER_PASSWORD
  required: true
- description: Username of the replication account for initialization.
  displayName: Replication Username
  name: PATRONI_REPLICATION_USERNAME
  required: true
  value: replication
- description: Password of the replication account for initialization.
  displayName: Repication Passsword
  from: '[a-zA-Z0-9]{32}'
  generate: expression
  name: PATRONI_REPLICATION_PASSWORD
  required: true
