version: "2"
# Actions to perform before analysis begins
# prepare:
#   fetch: Remote files to fetch (files are placed relative to the repo's root directory)
#     url: url to fetch
#       path: destination relative to repo's root directory

# Configuration of maintainability checks
# checks:
#   <name>
#     enabled: true|false
#     config: check configuration
# checks:
#   argument-count:
#     enabled: true
#     config:
#       threshold: 4
#   complex-logic:
#     enabled: true
#     config:
#       threshold: 4
#   file-lines:
#     enabled: true
#     config:
#       threshold: 250
#   method-complexity:
#     enabled: true
#     config:
#       threshold: 5
#   method-count:
#     enabled: true
#     config:
#       threshold: 20
#   method-lines:
#     enabled: true
#     config:
#       threshold: 25
#   nested-control-flow:
#     enabled: true
#     config:
#       threshold: 4
#   return-statements:
#     enabled: true
#     config:
#       threshold: 4
#   similar-code:
#     enabled: true
#     # config:
#     #   threshold: #language-specific defaults. overrides affect all languages.
#   identical-code:
#     enabled: true
#     # config:
#     #   threshold: #language-specific defaults. overrides affect all languages.

# Enable optional engines to run in addition to your analysis
# plugins:
#   <name>
#     enabled: true|false
#     channel: alternate channel to use (stable is default)
#     config: plugin configuration
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      config: workspace/.eslintrc.json


# Exclude files and/or directories from analysis
exclude_patterns:
  # Root
  - "backend/" # TODO temporary exclusion
  - "charts/"
  - "infra/"
  - "docker-compose.yml"
  - "realm-export-local.yml"
  # General
  - "**/.vscode/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/*.d.ts"
  # Workspace
  - "/workspace/.angular"
  - "/workspace/tools/"
  # Backend
