namespace Pidp.Models.Lookups;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public enum ProvinceCode
{
    Alberta = 1,
    BritishColumbia,
    Manitoba,
    NewBrunswick,
    NewfoundlandLabrador,
    NovaScotia,
    Ontario,
    PrinceEdwardIsland,
    Quebec,
    Saskatchewan,
    NorthwestTerritories,
    Nunavut,
    Yukon,
    Alabama,
    Alaska,
    AmericanSamoa,
    Arizona,
    Arkansas,
    California,
    Colorado,
    Connecticut,
    Delaware,
    DistrictOfColumbia,
    Florida,
    Georgia,
    Guam,
    Hawaii,
    Idaho,
    Illinois,
    Indiana,
    Iowa,
    Kansas,
    Kentucky,
    Louisiana,
    Maine,
    Maryland,
    Massachusetts,
    Michigan,
    Minnesota,
    Mississippi,
    Missouri,
    Montana,
    Nebraska,
    Nevada,
    NewHampshire,
    NewJersey,
    NewMexico,
    NewYork,
    NorthCarolina,
    NorthDakota,
    NorthernMarianaIslands,
    Ohio,
    Oklahoma,
    Oregon,
    Pennsylvania,
    PuertoRico,
    RhodeIsland,
    SouthCarolina,
    SouthDakota,
    Tennessee,
    Texas,
    USMinorOutlyingIslands,
    Utah,
    Vermont,
    VirginIslands,
    Virginia,
    Washington,
    WestVirginia,
    Wisconsin,
    Wyoming
}

[Table("ProvinceLookup")]
public class Province
{
    [Key]
    public ProvinceCode Code { get; set; }

    public string IsoCode { get; set; } = string.Empty;

    public CountryCode CountryCode { get; set; }

    public string Name { get; set; } = string.Empty;
}

public class ProvinceDataGenerator : ILookupDataGenerator<Province>
{
    public IEnumerable<Province> Generate() => new[]
    {
        new Province { Code = ProvinceCode.Alberta,                IsoCode = "AB", CountryCode = CountryCode.Canada,       Name = "Alberta"                              },
        new Province { Code = ProvinceCode.BritishColumbia,        IsoCode = "BC", CountryCode = CountryCode.Canada,       Name = "British Columbia"                     },
        new Province { Code = ProvinceCode.Manitoba,               IsoCode = "MB", CountryCode = CountryCode.Canada,       Name = "Manitoba"                             },
        new Province { Code = ProvinceCode.NewBrunswick,           IsoCode = "NB", CountryCode = CountryCode.Canada,       Name = "New Brunswick"                        },
        new Province { Code = ProvinceCode.NewfoundlandLabrador,   IsoCode = "NL", CountryCode = CountryCode.Canada,       Name = "Newfoundland and Labrador"            },
        new Province { Code = ProvinceCode.NovaScotia,             IsoCode = "NS", CountryCode = CountryCode.Canada,       Name = "Nova Scotia"                          },
        new Province { Code = ProvinceCode.Ontario,                IsoCode = "ON", CountryCode = CountryCode.Canada,       Name = "Ontario"                              },
        new Province { Code = ProvinceCode.PrinceEdwardIsland,     IsoCode = "PE", CountryCode = CountryCode.Canada,       Name = "Prince Edward Island"                 },
        new Province { Code = ProvinceCode.Quebec,                 IsoCode = "QC", CountryCode = CountryCode.Canada,       Name = "Quebec"                               },
        new Province { Code = ProvinceCode.Saskatchewan,           IsoCode = "SK", CountryCode = CountryCode.Canada,       Name = "Saskatchewan"                         },
        new Province { Code = ProvinceCode.NorthwestTerritories,   IsoCode = "NT", CountryCode = CountryCode.Canada,       Name = "Northwest Territories"                },
        new Province { Code = ProvinceCode.Nunavut,                IsoCode = "NU", CountryCode = CountryCode.Canada,       Name = "Nunavut"                              },
        new Province { Code = ProvinceCode.Yukon,                  IsoCode = "YT", CountryCode = CountryCode.Canada,       Name = "Yukon"                                },
        new Province { Code = ProvinceCode.Alabama,                IsoCode = "AL", CountryCode = CountryCode.UnitedStates, Name = "Alabama"                              },
        new Province { Code = ProvinceCode.Alaska,                 IsoCode = "AK", CountryCode = CountryCode.UnitedStates, Name = "Alaska"                               },
        new Province { Code = ProvinceCode.AmericanSamoa,          IsoCode = "AS", CountryCode = CountryCode.UnitedStates, Name = "American Samoa"                       },
        new Province { Code = ProvinceCode.Arizona,                IsoCode = "AZ", CountryCode = CountryCode.UnitedStates, Name = "Arizona"                              },
        new Province { Code = ProvinceCode.Arkansas,               IsoCode = "AR", CountryCode = CountryCode.UnitedStates, Name = "Arkansas"                             },
        new Province { Code = ProvinceCode.California,             IsoCode = "CA", CountryCode = CountryCode.UnitedStates, Name = "California"                           },
        new Province { Code = ProvinceCode.Colorado,               IsoCode = "CO", CountryCode = CountryCode.UnitedStates, Name = "Colorado"                             },
        new Province { Code = ProvinceCode.Connecticut,            IsoCode = "CT", CountryCode = CountryCode.UnitedStates, Name = "Connecticut"                          },
        new Province { Code = ProvinceCode.Delaware,               IsoCode = "DE", CountryCode = CountryCode.UnitedStates, Name = "Delaware"                             },
        new Province { Code = ProvinceCode.DistrictOfColumbia,     IsoCode = "DC", CountryCode = CountryCode.UnitedStates, Name = "District of Columbia"                 },
        new Province { Code = ProvinceCode.Florida,                IsoCode = "FL", CountryCode = CountryCode.UnitedStates, Name = "Florida"                              },
        new Province { Code = ProvinceCode.Georgia,                IsoCode = "GA", CountryCode = CountryCode.UnitedStates, Name = "Georgia"                              },
        new Province { Code = ProvinceCode.Guam,                   IsoCode = "GU", CountryCode = CountryCode.UnitedStates, Name = "Guam"                                 },
        new Province { Code = ProvinceCode.Hawaii,                 IsoCode = "HI", CountryCode = CountryCode.UnitedStates, Name = "Hawaii"                               },
        new Province { Code = ProvinceCode.Idaho,                  IsoCode = "ID", CountryCode = CountryCode.UnitedStates, Name = "Idaho"                                },
        new Province { Code = ProvinceCode.Illinois,               IsoCode = "IL", CountryCode = CountryCode.UnitedStates, Name = "Illinois"                             },
        new Province { Code = ProvinceCode.Indiana,                IsoCode = "IN", CountryCode = CountryCode.UnitedStates, Name = "Indiana"                              },
        new Province { Code = ProvinceCode.Iowa,                   IsoCode = "IA", CountryCode = CountryCode.UnitedStates, Name = "Iowa"                                 },
        new Province { Code = ProvinceCode.Kansas,                 IsoCode = "KS", CountryCode = CountryCode.UnitedStates, Name = "Kansas"                               },
        new Province { Code = ProvinceCode.Kentucky,               IsoCode = "KY", CountryCode = CountryCode.UnitedStates, Name = "Kentucky"                             },
        new Province { Code = ProvinceCode.Louisiana,              IsoCode = "LA", CountryCode = CountryCode.UnitedStates, Name = "Louisiana"                            },
        new Province { Code = ProvinceCode.Maine,                  IsoCode = "ME", CountryCode = CountryCode.UnitedStates, Name = "Maine"                                },
        new Province { Code = ProvinceCode.Maryland,               IsoCode = "MD", CountryCode = CountryCode.UnitedStates, Name = "Maryland"                             },
        new Province { Code = ProvinceCode.Massachusetts,          IsoCode = "MA", CountryCode = CountryCode.UnitedStates, Name = "Massachusetts"                        },
        new Province { Code = ProvinceCode.Michigan,               IsoCode = "MI", CountryCode = CountryCode.UnitedStates, Name = "Michigan"                             },
        new Province { Code = ProvinceCode.Minnesota,              IsoCode = "MN", CountryCode = CountryCode.UnitedStates, Name = "Minnesota"                            },
        new Province { Code = ProvinceCode.Mississippi,            IsoCode = "MS", CountryCode = CountryCode.UnitedStates, Name = "Mississippi"                          },
        new Province { Code = ProvinceCode.Missouri,               IsoCode = "MO", CountryCode = CountryCode.UnitedStates, Name = "Missouri"                             },
        new Province { Code = ProvinceCode.Montana,                IsoCode = "MT", CountryCode = CountryCode.UnitedStates, Name = "Montana"                              },
        new Province { Code = ProvinceCode.Nebraska,               IsoCode = "NE", CountryCode = CountryCode.UnitedStates, Name = "Nebraska"                             },
        new Province { Code = ProvinceCode.Nevada,                 IsoCode = "NV", CountryCode = CountryCode.UnitedStates, Name = "Nevada"                               },
        new Province { Code = ProvinceCode.NewHampshire,           IsoCode = "NH", CountryCode = CountryCode.UnitedStates, Name = "New Hampshire"                        },
        new Province { Code = ProvinceCode.NewJersey,              IsoCode = "NJ", CountryCode = CountryCode.UnitedStates, Name = "New Jersey"                           },
        new Province { Code = ProvinceCode.NewMexico,              IsoCode = "NM", CountryCode = CountryCode.UnitedStates, Name = "New Mexico"                           },
        new Province { Code = ProvinceCode.NewYork,                IsoCode = "NY", CountryCode = CountryCode.UnitedStates, Name = "New York"                             },
        new Province { Code = ProvinceCode.NorthCarolina,          IsoCode = "NC", CountryCode = CountryCode.UnitedStates, Name = "North Carolina"                       },
        new Province { Code = ProvinceCode.NorthDakota,            IsoCode = "ND", CountryCode = CountryCode.UnitedStates, Name = "North Dakota"                         },
        new Province { Code = ProvinceCode.NorthernMarianaIslands, IsoCode = "MP", CountryCode = CountryCode.UnitedStates, Name = "Northern Mariana Islands"             },
        new Province { Code = ProvinceCode.Ohio,                   IsoCode = "OH", CountryCode = CountryCode.UnitedStates, Name = "Ohio"                                 },
        new Province { Code = ProvinceCode.Oklahoma,               IsoCode = "OK", CountryCode = CountryCode.UnitedStates, Name = "Oklahoma"                             },
        new Province { Code = ProvinceCode.Oregon,                 IsoCode = "OR", CountryCode = CountryCode.UnitedStates, Name = "Oregon"                               },
        new Province { Code = ProvinceCode.Pennsylvania,           IsoCode = "PA", CountryCode = CountryCode.UnitedStates, Name = "Pennsylvania"                         },
        new Province { Code = ProvinceCode.PuertoRico,             IsoCode = "PR", CountryCode = CountryCode.UnitedStates, Name = "Puerto Rico"                          },
        new Province { Code = ProvinceCode.RhodeIsland,            IsoCode = "RI", CountryCode = CountryCode.UnitedStates, Name = "Rhode Island"                         },
        new Province { Code = ProvinceCode.SouthCarolina,          IsoCode = "SC", CountryCode = CountryCode.UnitedStates, Name = "South Carolina"                       },
        new Province { Code = ProvinceCode.SouthDakota,            IsoCode = "SD", CountryCode = CountryCode.UnitedStates, Name = "South Dakota"                         },
        new Province { Code = ProvinceCode.Tennessee,              IsoCode = "TN", CountryCode = CountryCode.UnitedStates, Name = "Tennessee"                            },
        new Province { Code = ProvinceCode.Texas,                  IsoCode = "TX", CountryCode = CountryCode.UnitedStates, Name = "Texas"                                },
        new Province { Code = ProvinceCode.USMinorOutlyingIslands, IsoCode = "UM", CountryCode = CountryCode.UnitedStates, Name = "United States Minor Outlying Islands" },
        new Province { Code = ProvinceCode.Utah,                   IsoCode = "UT", CountryCode = CountryCode.UnitedStates, Name = "Utah"                                 },
        new Province { Code = ProvinceCode.Vermont,                IsoCode = "VT", CountryCode = CountryCode.UnitedStates, Name = "Vermont"                              },
        new Province { Code = ProvinceCode.VirginIslands,          IsoCode = "VI", CountryCode = CountryCode.UnitedStates, Name = "Virgin Islands, U.S."                 },
        new Province { Code = ProvinceCode.Virginia,               IsoCode = "VA", CountryCode = CountryCode.UnitedStates, Name = "Virginia"                             },
        new Province { Code = ProvinceCode.Washington,             IsoCode = "WA", CountryCode = CountryCode.UnitedStates, Name = "Washington"                           },
        new Province { Code = ProvinceCode.WestVirginia,           IsoCode = "WV", CountryCode = CountryCode.UnitedStates, Name = "West Virginia"                        },
        new Province { Code = ProvinceCode.Wisconsin,              IsoCode = "WI", CountryCode = CountryCode.UnitedStates, Name = "Wisconsin"                            },
        new Province { Code = ProvinceCode.Wyoming,                IsoCode = "WY", CountryCode = CountryCode.UnitedStates, Name = "Wyoming"                              }
    };
}
