apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-cleanup-pipeline
  namespace: f088b1-tools
spec:
  params:
    - name: release_name
    - name: release_namespace
      default: f088b1-dev
  workspaces:
    - name: source
  tasks:
    - name: uninstall-pr
      workspaces:
        - name: source
          workspace: source
      params:
      - name: release_name
        value: $(params.release_name)
      - name: release_namespace
        value: $(params.release_namespace)
      taskRef:
        name: helm-uninstall