kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "backupcontainer.fullname" . }}
  labels:
    {{- include "backupcontainer.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.backup.backup_volume_class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.backup.backup_volume_size }}
