kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "backupcontainer.fullname" . }}-conf
  labels:
    {{- include "backupcontainer.labels" . | nindent 4 }}
data:
  backup.conf: |-
    # ============================================================
    # Databases:
    # ------------------------------------------------------------
    # List the databases you want backed up here.
    # Databases will be backed up in the order they are listed.
    #
    # The entries must be in one of the following forms:
    # - <Hostname/>/<DatabaseName/>
    # - <Hostname/>:<Port/>/<DatabaseName/>
    # - <DatabaseType>=<Hostname/>/<DatabaseName/>
    # - <DatabaseType>=<Hostname/>:<Port/>/<DatabaseName/>
    #
    # Examples:
    # - postgres=postgresql/my_database
    # - postgres=postgresql:5432/my_database
    # - mssql=mssql_server:1433/my_database
    # -----------------------------------------------------------
    # Cron Scheduling:
    # -----------------------------------------------------------
    # List your backup and verification schedule(s) here as well.
    # The schedule(s) must be listed as cron tabs that 
    # execute the script in 'scheduled' mode:
    #   - ./backup.sh -s
    #
    # Examples (assuming system's TZ is set to PST):
    # - 0 1 * * * default ./backup.sh -s
    #   - Run a backup at 1am Pacific every day.
    #
    # - 0 4 * * * default ./backup.sh -s -v all
    #   - Verify the most recent backups for all datbases
    #     at 4am Pacific every day.
    # -----------------------------------------------------------

    postgres={{ .Values.backup.database_service_name }}:5432/{{ .Values.backup.database_name }}
    # postgres=metabase-database:5432/metabase

    0 * * * * default bash ./backup.sh -s
    30 * * * * default bash ./backup.sh -s -v all
