{{- if .Values.ftp.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "backupcontainer.fullname" . }}-ftp
  labels:
    {{- include "backupcontainer.labels" . | nindent 4 }}
type: Opaque
stringData:
  ftp-url: {{ .Values.ftp.ftp_url }}
  ftp-user: {{ .Values.ftp.ftp_user }}
  ftp-password: {{ .Values.ftp.ftp_password }}
  ftp-url-host: {{ .Values.ftp.ftp_url_host }}
{{- end }}