kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "backup-verification"
  labels:
    {{- include "backupcontainer.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.backup.verification_volume_class }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.verification_volume_size }}