{{- if .Values.webhook.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "backupcontainer.fullname" . }}-webhook
  labels:
    {{- include "backupcontainer.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.webhook.webhook_url }}
  webhook-url-host: {{ .Values.webhook.webhook_url_host }}
{{- end }}