{{- if .Values.rabbitmq.autoCreate }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pidp.fullname" . }}-createrabbitmqhost
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    {{- include "pidp.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: create-rabbitmq-vhost
        image: "docker.io/bitnami/rabbitmq:3.11.9-debian-11-r1"
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - >
            rabbitmqctl add_vhost pr-{{ $release }}
            rabbitmqctl set_permissions -p pr-{{ $release }} pidp ".*" ".*" ".*"       
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
