{{- if hasPrefix "pr-" .Release.Name }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pidp.fullname" . }}-deleterabbitmqhost
  annotations:
    helm.sh/hook: post-delete
     helm.sh/hook-delete-policy: hook-succeeded
  labels:
    {{- include "pidp.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: delete-rabbitmq-vhost
        image: ghcr.io/bashbang/util:release
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - >
            echo "delete the pr-{{ $release }} vhost and remove permissions for the pidp user to use it." ;
    
            curl -u rabbitmq:rabbitmq -X DELETE http://rabbitmq:15672/api/vhosts/{{ $release }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
