{{ $release := .Release.Name }}
{{ $domain := .Values.global.vanityURL }}
{{ $isProd := contains "prod" $ocEnv }}

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for job that activates pod to send endorsement reminder emails
    tags: cronjob
  name: scheduler-pod-launcher
objects:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: '${CRON_NAME}'
    spec:
      concurrencyPolicy: Forbid
      suspend: false
      schedule: '${CRON_SCHEDULE}' 
      # Cleaning Up After a Cron Job
      successfulJobsHistoryLimit: 3 
      failedJobsHistoryLimit: 1    
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - command:
                  - bash
                  - '-c'
                  - >-
                    echo -e "-------- RUNNING CRON --------\n"
                env:
                  - name: ConnectionStrings__PidpDatabase
                    value: "Host=localhost;Port=5433;Database=postgres;Username=postgres;Password=postgres"
                  - name: ChesClient__TokenUrl
                    valueFrom:
                      configMapKeyRef:
                        name: ches
                        key: ChesClient__TokenUrl
                  - name: ChesClient__ClientId
                    valueFrom:
                      configMapKeyRef:
                        name: ches
                        key: ChesClient__ClientId
                  - name: ChesClient__ClientSecret
                    valueFrom:
                      configMapKeyRef:
                        name: ches
                        key: ChesClient__ClientSecret
                  - name: ChesClient__Url
                    valueFrom:
                      configMapKeyRef:
                        name: ches
                        key: ChesClient__Url
                  - name: ChesClient__Enabled
                    valueFrom:
                      configMapKeyRef:
                        name: ches
                        key: ChesClient__Enabled
                  - name: ASPNETCORE_ENVIRONMENT
                    value: {{ .Values.aspnetcore.environment }}
                  - name: ApplicationUrl
                    value: "https://{{ if $isProd }}{{else}}{{ $release }}.{{end}}{{ $domain }}"
                  - name: MailServer__EnableSsl
                    valueFrom:
                      configMapKeyRef:
                        name: mail-settings
                        key: MailServer__EnableSsl
                  - name: MailServer__Url
                    valueFrom:
                      configMapKeyRef:
                        name: mail-settings
                        key: MailServer__Url
                  - name: MailServer__Port
                    valueFrom:
                      configMapKeyRef:
                        name: mail-settings
                        key: MailServer__Port

                - image: >-
                    image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/endorsement-reminder:latest
                  limits:
                    cpu: 500m
                    memory: 2Gi
                  name: '${CRON_NAME}'
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  resources: null
              restartPolicy: Never
parameters:
  - description: 'Cron-like schedule expression. TEST SCHEDULE EVERY TWO MINUTES'
    name: CRON_SCHEDULE
    value: '*/2 * * * *'
  - name: CRON_NAME
    value: scheduler-pod-launcher
  - description: 'Environment name'
    name: ENV_NAME
    required: true
