apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template for job that activates pod to send endorsement reminder emails
    tags: cronjob
  name: scheduler-pod-launcher
objects:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: '${CRON_NAME}'
    spec:
      concurrencyPolicy: Forbid
      suspend: false
      schedule: '${CRON_SCHEDULE}' 
      # Cleaning Up After a Cron Job
      successfulJobsHistoryLimit: 3 
      failedJobsHistoryLimit: 1    
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - image: >-
                    image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/endorsement-reminder:latest
                  limits:
                    cpu: 500m
                    memory: 2Gi
                  name: '${CRON_NAME}'
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  resources: null
              restartPolicy: Never
parameters:
  - description: 'Cron-like schedule expression. Default: Once a day at 8:00 AM.'
    name: CRON_SCHEDULE
    value: '0 8 * * *'
  - name: CRON_NAME
    value: scheduler-pod-launcher
  - description: 'Environment name'
    name: ENV_NAME
    required: true
