kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    name: {{ .Values.appName }}
spec:
  ports:
  - name: 8080-tcp
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP
