# Midas Probe SA is used by a pod running Python to check the availability of pods within a namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: midas-probe-view
    namespace: {{ .Values.namespace }}
subjects:
    - kind: ServiceAccount
      name: midas-probe
      namespace: {{ .Values.namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'view'
---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: midas-probe
    namespace: {{ .Values.namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: system:image-puller-midas-probe-{{ .Values.namespace }}
    namespace: {{ .Values.licensePlate }}-tools
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: midas-probe
    namespace: {{ .Values.namespace }}