kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app_name }}-master
  namespace: {{ .Values.license_plate }}-{{ .Values.environment }}
  labels:
    {{- include "chart.common-labels" . }}
spec:
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cluster-name: {{ .Values.app_name }}
    role: master
    app.kubernetes.io/name: {{ .Values.app_name }}
    app: {{ .Values.app_name }}
  sessionAffinity: None
  type: ClusterIP
