kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.license_plate }}-{{ .Values.environment }}
  labels:
    {{- include "chart.common-labels" . }}
spec:
  serviceName: {{ .Values.app_name }}
  revisionHistoryLimit: 10
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        cluster-name: {{ .Values.app_name }}
        app.kubernetes.io/name: {{ .Values.app_name }}
        app: {{ .Values.app_name }}
      annotations:
        prometheus.io/port: '9187'
        prometheus.io/scrape: 'true'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: statefulset
                    operator: In
                    values:
                      - {{ .Values.app_name }}
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: {{ .Values.app_name }}-get-ts-port
          # This container obtains the TS port that we use to connect to Gold in the patroni config inside the main container
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          args:
            - /bin/sh
            - '-c'
            - '/get-ts-port.sh'
          resources:
            requests:
              cpu: {{ .Values.stateful_initrequests_cpu }}
              memory: {{ .Values.stateful_initrequests_memory }}
          volumeMounts:
            - name: {{ .Values.app_name }}-intercom
              mountPath: /intercom
            - name: {{ .Values.app_name }}-get-ts-port
              mountPath: /get-ts-port.sh
              subPath: get-ts-port.sh
      containers:
        - env:
            #TODO: Remove POD_IP in favor of PATRONI_KUBERNETES_POD_IP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            #          - name: PATRONI_KUBERNETES_USE_ENDPOINTS
            #            value: 'true'
            #          - name: PATRONI_KUBERNETES_POD_IP
            #            valueFrom:
            #              fieldRef:
            #                apiVersion: v1
            #                fieldPath: status.podIP
            #          - name: PATRONI_KUBERNETES_PORTS
            #            value: '{[{"name": "postgresql", "port": 5432}]}'
            - name: PATRONI_KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATRONI_KUBERNETES_LABELS
              value: '{"cluster-name": "{{ .Values.license_plate }}", "app.kubernetes.io/name": "patroni"}'
            - name: PATRONI_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: superuser-username
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: PATRONI_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: superuser-password
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: PATRONI_REPLICATION_USERNAME
              valueFrom:
                secretKeyRef:
                  key: replication-username
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: PATRONI_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: replication-password
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  key: app-db-username
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-db-password
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: APP_DATABASE
              valueFrom:
                secretKeyRef:
                  key: app-db-name
                  name: {{ .Values.environment }}-{{ .Values.app_name }}-secret
            - name: PATRONI_SCOPE
              value: {{ .Values.app_name }}
            - name: PATRONI_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PATRONI_LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: PATRONI_POSTGRESQL_DATA_DIR
              value: /home/postgres/pgdata/pgroot/data
            - name: PATRONI_POSTGRESQL_PGPASS
              value: /tmp/pgpass
            - name: PATRONI_POSTGRESQL_LISTEN
              value: 0.0.0.0:5432
            - name: PATRONI_RESTAPI_LISTEN
              value: 0.0.0.0:8008
            - name: CLUSTER
              value: {{ .Values.cluster }}
          # image: {{ .Values.image_registry }}/{{ .Values.license_plate }}-tools/patroni-postgres:latest
          image: 'public.ecr.aws/h0h9t7p1/patroni-postgres:12.4-latest'
          imagePullPolicy: Always
          name: patroni
          ports:
            - containerPort: 8008
              protocol: TCP
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.stateful_requests_cpu }}
              memory: {{ .Values.stateful_requests_memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - |
                set -Eeuo pipefail && df "${PATRONI_POSTGRESQL_DATA_DIR:-/home/postgres/pgdata}" --output=pcent | tail -n 1 | awk '{if ($1+0 > 90) exit 1; else exit 0;}' && pg_isready -q && curl -s localhost:8008/readiness | jq -e ". | select(.state == \"running\")"
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 5
          name: postgresql
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/env
                  - bash
                  - '-c'
                  - |
                    # switch leader pod if the current pod is the leader
                    if curl --fail http://localhost:8008/read-write; then
                      patronictl switchover --force
                    fi
          livenessProbe:
            exec:
              command:
                - /usr/bin/env
                - bash
                - '-c'
                - |
                  set -Eeuo pipefail && curl -s localhost:8008/liveness | jq -e ". | select(.state == \"running\")"
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: postgresql
              mountPath: /home/postgres/pgdata
            - name: {{ .Values.app_name }}-entrypoint
              mountPath: /usr/bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: {{ .Values.app_name }}-intercom
              mountPath: /intercom
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: {{ .Values.app_name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.app_name }}-entrypoint
        configMap:
          name: {{ .Values.app_name }}-entrypoint
          defaultMode: 448
      - name: {{ .Values.app_name }}-intercom
        emptyDir: {}
      - name: {{ .Values.app_name }}-get-ts-port
        configMap:
          name: {{ .Values.app_name }}-get-ts-port
          defaultMode: 0555
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: netapp-block-standard
        labels:
          cluster-name: {{ .Values.app_name }}
          app.kubernetes.io/name: {{ .Values.app_name }}
          app: {{ .Values.app_name }}
        name: postgresql
      spec:
        storageClassName: netapp-block-standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volume_size }}
        volumeMode: Filesystem
      status:
        phase: Pending
  replicas: {{ .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      cluster-name: {{ .Values.app_name }}
      app.kubernetes.io/name: {{ .Values.app_name }}
      app: {{ .Values.app_name }}
  