apiVersion: v2
appVersion: 1.30.3
description: Telegraf is an agent written in Go for collecting, processing, aggregating,
  and writing metrics.
home: https://www.influxdata.com/time-series-platform/telegraf/
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
keywords:
- telegraf
- collector
- timeseries
- influxdata
- influxdb
- agent
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
name: telegraf
sources:
- https://github.com/influxdata/helm-charts/tree/master/charts/telegraf
- https://github.com/influxdata/helm-charts/
version: 1.8.48
