apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-push-trigger-template
  namespace: f088b1-tools
spec: 
  params:
    - name: git-revision
      description: The git revision (SHA)
    - name: git-repository-url
      description: The git repository url
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: git-short-sha
      description: Trunkated SHA of the git commit
    - name: git-branch-name
      description: The name of the branch
    - name: release-namespace
      description: Target deployment namespace
    - name: release-name
      description: Name of the release
    - name: values-file
      description: Helm deployment answer files
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cicd-pipeline-run-$(tt.params.release-name)-$(tt.params.git-short-sha)-
      spec:
        pipelineRef:
          name: cicd-pipeline
        serviceAccountName: pipeline
        params:
          - name: git-url
            value: git@github.com:bcgov/moh-pidp.git
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: git-short-sha
            value: $(tt.params.git-short-sha)
          - name: image-tag
            value: $(tt.params.git-branch-name)
          - name: release_name
            value: $(tt.params.release-name)
          - name: release_namespace
            value: $(tt.params.release-namespace)
          - name: values_file
            value: $(tt.params.values-file)
        workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 1Gi
        - name: dockerconfig
          secret:
            secretName: pipeline-dockercfg-w5mgt
