apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pr-cleanup-trigger-template
  namespace: f088b1-tools
spec: 
  params:
    - name: git-pr-number
      description: GitHUb PR number
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pr-cleanup-pipeline-run-$(tt.params.git-pr-number)
      spec:
        pipelineRef:
          name: pr-cleanup-pipeline
        serviceAccountName: pipeline
        params:
          - name: release_name
            value: $(tt.params.git-pr-number)
          - name: release_namespace
            value: f088b1-dev
        workspaces:
        - name: source
          emptyDir: {}
