# Metabase-database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metabase.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "metabase.name" . }}-database
    helm.sh/chart: {{ include "metabase.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "namespace": "openshift",
            "name": "postgresql:{{ .Values.database.postgresql_version }}"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name:: {{ include "metabase.fullname" . }}-database
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name:: {{ include "metabase.fullname" . }}-database
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ include "metabase.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "metabase.fullname" . }}
      containers:
        - name: postgresql
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-username
                  name: {{ include "metabase.fullname" . }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ include "metabase.fullname" . }}
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ include "metabase.fullname" . }}
          image: '{{ .Values.database.postgresql_image }}:{{ .Values.database.postgresql_version }}'
          imagePullPolicy: {{ .Values.database.pullPolicy }}
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10       
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: {{ .Values.database.memory_limit }}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: {{ include "metabase.fullname" . }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler