apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  name: {{ include "metabase.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "metabase.name" . }}-database
    helm.sh/chart: {{ include "metabase.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: postgresql
      nodePort: 0
      port: {{ .Values.database.port }}
      protocol: TCP
      targetPort: 5432
  selector:
    name: {{ include "metabase.fullname" . }}-database
  type: ClusterIP