apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.storage.pvc_capacity }}"