apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-databae-host: '{.data[''database-host'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-username: '{.data[''database-username'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'

stringData:
  database-host: {{ .Values.database.host }}
  database-name: {{ .Values.database.name }}
  database-username: {{ .Values.database.username }}
  database-password: {{ .Values.database.password }}