# PR Helm values
global:
  vanityURL: "healthprovideridentityportal.gov.bc.ca"
  commit_sha: ""
  image:
    registry: image-registry.openshift-image-registry.svc:5000/d8a8f9-tools
    tag: develop
  license_plate: "d8a8f9"

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 1
  fluentbit:
    enabled: false

frontend:
  replicaCount: 1
  settings:
    environmentName: dev
    keycloak:
      url: https://common-logon-dev.hlth.gov.bc.ca/auth

webapi:
  replicaCount: 1
  aspnetcore:
    environment: Staging
  fluentbit:
    enabled: false

plr-intake:
  replicaCount: 1

rabbitmq:
  autoCreate: true
  host: rabbitmq://pidp:password@rabbitmq:5672/