# PR Helm values
global:
  vanityURL: "healthprovideridentityportal.gov.bc.ca"
  commit_sha: ""
  image:
    tag: develop

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 1

frontend:
  replicaCount: 1
  settings:
    environmentName: dev
    keycloak:
      url: https://common-logon-dev.hlth.gov.bc.ca/auth

webapi:
  replicaCount: 1

plr-intake:
  replicaCount: 1