# PR Helm values
global:
  vanityURL: "healthprovideridentityportal.gov.bc.ca"
  commit_sha: ""
  image:
    registry: image-registry.openshift-image-registry.svc:5000/f088b1-tools
    tag: main
  license_plate: f088b1


database:
  autoCreate: false
  # databaseHost: dev-patroni
# existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 3
  fluentbit:
    enabled: true
  serverBlock: |-
    server {
      listen 8080;
      server_name localhost *.gov.bc.ca;
      location / {
        proxy_pass http://prod-frontend:8080/;
      }
      location ^~ /api/ {
        proxy_pass http://prod-webapi:8080/api/;
      }
      location ^~ /api/v1/ {
        proxy_pass http://prod-webapi:8080/api/;
      }
      location ^~ /api/v1/PLRHL7 {
        proxy_pass http://prod-webapi:8080/api/PLRHL7;
        proxy_set_header  X-SSL-CERT $ssl_client_escaped_cert;
      }
      location  ^~ /midas/ {
        proxy_pass http://midas-probe:80/midas/;
      }
      # Deny all attempts to access hidden files such as .htaccess or .htpasswd
      location ~ /\. {
        deny all;
      }
      # required for metrics exporter
      location /status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }
    }
    server {
      listen 8443 ssl;
      server_name localhost *.gov.bc.ca;
      ssl_certificate certs/tls.crt;
      ssl_certificate_key certs/tls.key;
      ssl_verify_client optional_no_ca;
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_client_certificate certs/plr/trusted-ca-certs.pem;
      set $CSP_style  "style-src    'self' 'unsafe-inline' *.googleapis.com *.gstatic.com https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css";
      set $CSP_font   "font-src     'self' data: *.googleapis.com *.gstatic.com";
      set $CSP_frame  "frame-ancestors 'self'  *.oidc.gov.bc.ca oidc.gov.bc.ca";
      set $CSP_SCRIPT "script-src 'self' 'unsafe-inline' https://code.jquery.com/jquery-3.6.0.min.js";
      set $CSP        "default-src  'self' 'unsafe-inline' *.hlth.gov.bc.ca ; ${CSP_style} ; ${CSP_font} ; ${CSP_SCRIPT} ; ${CSP_frame}";
      add_header Content-Security-Policy $CSP;
      add_header X-Frame-Options "ALLOW-FROM dev.oidc.gov.bc.ca oidc.gov.bc.ca" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Referrer-Policy "no-referrer-when-downgrade";
      location / {
        proxy_pass http://prod-frontend:8080/;
      }
      location ^~ /api/ {
        proxy_pass http://prod-webapi:8080/api/;
      }
      location ^~ /api/v1/ {
        proxy_pass http://prod-webapi:8080/api/;
      }
      location ^~ /api/v1/PLRHL7 {
        proxy_pass http://prod-webapi:8080/api/PLRHL7;
        proxy_set_header  X-SSL-CERT $ssl_client_escaped_cert;
      }
      location  ^~ /midas/ {
        proxy_pass http://midas-probe:80/midas/;
      }
      # Deny all attempts to access hidden files such as .htaccess or .htpasswd
      location ~ /\. {
        deny all;
      }
      # required for metrics exporter
      location /status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }
    }
    server {
      listen 8543 ssl;
      server_name localhost *.gov.bc.ca;
      ssl_certificate certs/tls.crt;
      ssl_certificate_key certs/tls.key;
      ssl_verify_client optional_no_ca;
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_client_certificate certs/plr/trusted-ca-certs.pem;
      set $CSP_style  "style-src    'self' 'unsafe-inline' *.googleapis.com *.gstatic.com; ";
      set $CSP_font   "font-src     'self' data: *.googleapis.com *.gstatic.com; ";
      set $CSP_frame  "frame-ancestors 'self'  *.oidc.gov.bc.ca oidc.gov.bc.ca";
      set $CSP        "default-src  'self' ; ${CSP_style} ${CSP_font} ${CSP_frame}";
      add_header Content-Security-Policy $CSP;
      add_header X-Frame-Options "ALLOW-FROM dev.oidc.gov.bc.ca oidc.gov.bc.ca" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header Referrer-Policy "no-referrer-when-downgrade";
      location ^~ /api/v1/PLRHL7 {
        proxy_pass http://prod-plr-intake:8080/api/PLRHL7;
        proxy_set_header  X-SSL-CERT $ssl_client_escaped_cert;
      }
      # Deny all attempts to access hidden files such as .htaccess or .htpasswd
      location ~ /\. {
        deny all;
      }
      # required for metrics exporter
      location /status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }
    }

frontend:
  replicaCount: 3
  settings:
    environmentName: prod
    keycloak:
      url: https://common-logon.hlth.gov.bc.ca/auth

webapi:
  replicaCount: 3
  aspnetcore:
    environment: Production
  fluentbit:
    enabled: true

plr-intake:
  replicaCount: 2

rabbitmq:
  autoCreate: true
  host: rabbitmq://pidp:password@rabbitmq:5672/