# PR Helm values
global:
  vanityURL: "healthprovideridentityportal.gov.bc.ca"
  commit_sha: ""
  image:
    registry: image-registry.openshift-image-registry.svc:5000/f088b1-tools
    tag: test
  license_plate: "f088b1"

database:
  autoCreate: false
  # databaseHost: dev-patroni
  # existingSecret: dev-patroni-secret

redis:
  enabled: false
  auth:
    existingSecret: redis
    existingSecretPasswordKey: database-password

nginx:
  replicaCount: 2

frontend:
  replicaCount: 3
  settings:
    environmentName: test
    keycloak:
      url: https://common-logon-test.hlth.gov.bc.ca/auth

webapi:
  replicaCount: 3
  aspnetcore:
    environment: Staging

plr-intake:
  replicaCount: 2

rabbitmq:
  autoCreate: true
  host: rabbitmq://pidp:password@rabbitmq:5672/