namespace PlrIntake.Models.Lookups;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table(nameof(Expertise))]
public class Expertise
{
    [Key]
    public string Code { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
}

public class ExpertiseDataGenerator : ILookupDataGenerator<Expertise>
{
    public IEnumerable<Expertise> Generate() => new[]
    {
        new Expertise { Code = "MS",       Name = "Management Studies"                                              },
        new Expertise { Code = "NON-SPEC", Name = "Non-Specialist"                                                  },
        new Expertise { Code = "NUCRX",    Name = "Nuclear Pharmacy"                                                },
        new Expertise { Code = "NUTRX",    Name = "Nutrition Pharmacy"                                              },
        new Expertise { Code = "ONCRX",    Name = "Oncology Pharmacy"                                               },
        new Expertise { Code = "OP",       Name = "Oral Medicine and Oral Pathology"                                },
        new Expertise { Code = "ORD",      Name = "Oral and Maxillofacial Radiology"                                },
        new Expertise { Code = "ORTH",     Name = "Orthodontics"                                                    },
        new Expertise { Code = "OS",       Name = "Oral Maxillofacial Surgery"                                      },
        new Expertise { Code = "PED",      Name = "Pediatric Dentistry"                                             },
        new Expertise { Code = "PER",      Name = "Periodontics"                                                    },
        new Expertise { Code = "PHPHARM",  Name = "Pharmacotherapy"                                                 },
        new Expertise { Code = "PRO",      Name = "Prosthodontics"                                                  },
        new Expertise { Code = "PSYRX",    Name = "Psychiatric Pharmacy"                                            },
        new Expertise { Code = "SMD1",     Name = "Addiction Medicine"                                              },
        new Expertise { Code = "SMD10",    Name = "Certified Independent Medical Examiner"                          },
        new Expertise { Code = "SMD100",   Name = "Medical Disorders of Pregnancy"                                  },
        new Expertise { Code = "LPNOR",    Name = "Operating Room"                                                  },
        new Expertise { Code = "SMD101",   Name = "Cardiovascular Disease"                                          },
        new Expertise { Code = "SMD104",   Name = "Chemical, Biological, Radiological and Nuclear Warfare Medicine" },
        new Expertise { Code = "SMD11",    Name = "Chemical Dependency"                                             },
        new Expertise { Code = "SMD12",    Name = "Child and Adolescent Psychiatry"                                 },
        new Expertise { Code = "SMD13",    Name = "Chronic Pain Management"                                         },
        new Expertise { Code = "SMD14",    Name = "Clinical Hypnosis"                                               },
        new Expertise { Code = "SMD15",    Name = "Colon & Rectal Surgery"                                          },
        new Expertise { Code = "SMD16",    Name = "Corneal & Extraocular Disease"                                   },
        new Expertise { Code = "SMD17",    Name = "Counseling"                                                      },
        new Expertise { Code = "SMD18",    Name = "Critical Care Medicine"                                          },
        new Expertise { Code = "SMD19",    Name = "Dermatology"                                                     },
        new Expertise { Code = "SMD2",     Name = "Adolescent Medicine"                                             },
        new Expertise { Code = "CCFPEM",   Name = "Certificant; CFPC(E.M.)"                                         },
        new Expertise { Code = "CMCE",     Name = "Community Medicine Certification"                                },
        new Expertise { Code = "CTI",      Name = "Computed Tomography Imaging"                                     },
        new Expertise { Code = "DPH",      Name = "Dental Public Health"                                            },
        new Expertise { Code = "DS",       Name = "Dental Sciences"                                                 },
        new Expertise { Code = "END",      Name = "Endodontics"                                                     },
        new Expertise { Code = "ERN1",     Name = "General Medicine"                                                },
        new Expertise { Code = "ERN10",    Name = "Critical/ Intensive Care"                                        },
        new Expertise { Code = "ERN11",    Name = "Occupational Health"                                             },
        new Expertise { Code = "ERN12",    Name = "Home Care"                                                       },
        new Expertise { Code = "ERN13",    Name = "Geriatric / Long Term Care"                                      },
        new Expertise { Code = "ERN14",    Name = "Community Health"                                                },
        new Expertise { Code = "ERN15",    Name = "Ambulatory Care"                                                 },
        new Expertise { Code = "ERN16",    Name = "Nursing Administration"                                          },
        new Expertise { Code = "ERN17",    Name = "Teaching"                                                        },
        new Expertise { Code = "ERN18",    Name = "Research"                                                        },
        new Expertise { Code = "ERN19",    Name = "Telehealth"                                                      },
        new Expertise { Code = "ERN2",     Name = "General Surgery"                                                 },
        new Expertise { Code = "CCFP",     Name = "Certificant; CFPC"                                               },
        new Expertise { Code = "ERN3",     Name = "Pediatrics"                                                      },
        new Expertise { Code = "ERN4",     Name = "Maternal / Newborn"                                              },
        new Expertise { Code = "ERN5",     Name = "Psychiatric/ Mental Health"                                      },
        new Expertise { Code = "ERN6",     Name = "Oncology"                                                        },
        new Expertise { Code = "ERN7",     Name = "Rehabilitation"                                                  },
        new Expertise { Code = "ERN8",     Name = "Operating / Recovery Room"                                       },
        new Expertise { Code = "ERN9",     Name = "Emergency Care/ Prehospital"                                     },
        new Expertise { Code = "GPDEN",    Name = "General Practice"                                                },
        new Expertise { Code = "GPMD",     Name = "General Practice"                                                },
        new Expertise { Code = "GPPHARM",  Name = "General Practice"                                                },
        new Expertise { Code = "LPNDIAL",  Name = "Dialysis"                                                        },
        new Expertise { Code = "LPNIMMUN", Name = "Immunization"                                                    },
        new Expertise { Code = "AMD35",    Name = "Nuclear Medicine - Full"                                         },
        new Expertise { Code = "AMD36",    Name = "Sleep Interpreter - Respiratory Dis."                            },
        new Expertise { Code = "AMD37",    Name = "Magnetic Resonance - Limited"                                    },
        new Expertise { Code = "AMD38",    Name = "Pulm Director - Level II"                                        },
        new Expertise { Code = "AMD39",    Name = "Pulm Director - Level III"                                       },
        new Expertise { Code = "AMD4",     Name = "Craniosacral Therapy(Complementary)"                             },
        new Expertise { Code = "AMD40",    Name = "Pulm Director - Level IV"                                        },
        new Expertise { Code = "AMD41",    Name = "Sleep Director -Full"                                            },
        new Expertise { Code = "AMD42",    Name = "Sleep Director - Pediatric Disorders"                            },
        new Expertise { Code = "AMD43",    Name = "Sleep Director - Respiratory Disorders"                          },
        new Expertise { Code = "AMD44",    Name = "Homeopathy (Complementary)"                                      },
        new Expertise { Code = "AMD45",    Name = "Ultrasound - Obstetrical / Gynecology"                           },
        new Expertise { Code = "AMD46",    Name = "Echocardiography -Restricted"                                    },
        new Expertise { Code = "AMD47",    Name = "Ultasound - Non-Specialist"                                      },
        new Expertise { Code = "AMD48",    Name = "Nuclear Medicine - Restricted"                                   },
        new Expertise { Code = "AMD49",    Name = "Addiction Medicine"                                              },
        new Expertise { Code = "AMD5",     Name = "Doctor of Osteopathy"                                            },
        new Expertise { Code = "AMD50",    Name = "Customized Nutritional Therapy(Comp.)"                           },
        new Expertise { Code = "AMD51",    Name = "Ultrasound -Abortion Transvaginal"                               },
        new Expertise { Code = "AMD52",    Name = "Ultrasound - Abortion Trans - abdominal"                         },
        new Expertise { Code = "AMD53",    Name = "Anti-Aging Medicine(Complementary)"                              },
        new Expertise { Code = "AMD54",    Name = "Primordial Sound Meditation(Complementary)"                      },
        new Expertise { Code = "AMD55",    Name = "Ayurveda(Complementary)"                                         },
        new Expertise { Code = "AMD56",    Name = "Fluoroscopically-guided needle placements"                       },
        new Expertise { Code = "AMD57",    Name = "Magnetic Resonance - Cardiac"                                    },
        new Expertise { Code = "AMD58",    Name = "PET -Positron Emission Tomography"                               },
        new Expertise { Code = "AMD6",     Name = "Electrocardiogram"                                               },
        new Expertise { Code = "AMD7",     Name = "Electroencephalography"                                          },
        new Expertise { Code = "AMD8",     Name = "Electromyography"                                                },
        new Expertise { Code = "AMD9",     Name = "Evoked Potential Auditory"                                       },
        new Expertise { Code = "BI",       Name = "Breast Imaging"                                                  },
        new Expertise { Code = "A225",     Name = "Max / Fax Surgery"                                               },
        new Expertise { Code = " A240",    Name = "Medical Imaging"                                                 },
        new Expertise { Code = "A385",     Name = "Pulmonary Diseases"                                              },
        new Expertise { Code = "AMD1",     Name = "Acupuncture"                                                     },
        new Expertise { Code = "AMD10",    Name = "Evoked Potential Somatosensory"                                  },
        new Expertise { Code = "AMD11",    Name = "Evoked Potential Visual"                                         },
        new Expertise { Code = "AMD12",    Name = "Evoked Potential(EP)"                                            },
        new Expertise { Code = "AMD13",    Name = "Functional Medicine(Complementary)"                              },
        new Expertise { Code = "AMD14",    Name = "Herbal Therapy(Complementary)"                                   },
        new Expertise { Code = "AMD15",    Name = "Kinesiology(Complementary)"                                      },
        new Expertise { Code = "AMD16",    Name = "Magnetic Resonance - Full"                                       },
        new Expertise { Code = "AMD17",    Name = "Cardiac Nuclear Imaging"                                         },
        new Expertise { Code = "AMD18",    Name = "Nuclear Medicine - Limited"                                      },
        new Expertise { Code = "AMD19",    Name = "Ultrasound - Opthalmology"                                       },
        new Expertise { Code = "AMD2",     Name = "Echocardiography -Full Adult"                                    },
        new Expertise { Code = "AMD20",    Name = "Echocardiography - Full Pediatric"                               },
        new Expertise { Code = "AMD21",    Name = "Pulm Interpretation-Level II"                                    },
        new Expertise { Code = "AMD22",    Name = "Pulm Interpretation-Level III"                                   },
        new Expertise { Code = "AMD23",    Name = "Pulm Interpretation-Level IV"                                    },
        new Expertise { Code = "AMD24",    Name = "Reiki Therapy(Complementary)"                                    },
        new Expertise { Code = "AMD25",    Name = "Thought Field Therapy(Complementary)"                            },
        new Expertise { Code = "AMD26",    Name = "Transcendental Meditation(Comp.)"                                },
        new Expertise { Code = "AMD27",    Name = "Echocardiography -Transesophageal"                               },
        new Expertise { Code = "AMD28",    Name = "Trigger Point Therapy"                                           },
        new Expertise { Code = "AMD29",    Name = "Ultrasound -Full"                                                },
        new Expertise { Code = "AMD3",     Name = "Cardiac Stress Testing"                                          },
        new Expertise { Code = "AMD30",    Name = "Ultrasound -Urology"                                             },
        new Expertise { Code = "AMD31",    Name = "Ultrasound -Vascular"                                            },
        new Expertise { Code = "AMD32",    Name = "Vestibular Testing - Director"                                   },
        new Expertise { Code = "AMD33",    Name = "Vestibular Testing - Interpretor"                                },
        new Expertise { Code = "AMD34",    Name = "Chelation Therapy(Complementary)"                                },
        new Expertise { Code = "480",      Name = "Thoracic Surgery(Gen.Sur.)"                                      },
        new Expertise { Code = "481",      Name = "Thoracic Surgery(General / Cardiac)"                             },
        new Expertise { Code = "490",      Name = "Vascular Surgery"                                                },
        new Expertise { Code = "510",      Name = "Clinical Pharmacology"                                           },
        new Expertise { Code = "512",      Name = "Colorectal Surgery"                                              },
        new Expertise { Code = "515",      Name = "Critical Care medicine"                                          },
        new Expertise { Code = "520",      Name = "General Surgical Oncology"                                       },
        new Expertise { Code = "530",      Name = "Gynecology Oncology"                                             },
        new Expertise { Code = "535",      Name = "Gynecology Reprod. Endocrin. & Infert."                          },
        new Expertise { Code = "540",      Name = "Transfusion Medicine"                                            },
        new Expertise { Code = "545",      Name = "Maternal - Fetal Medicine"                                       },
        new Expertise { Code = "550",      Name = "Clinician Investigator Program"                                  },
        new Expertise { Code = "555",      Name = "Neonatal - Perinatal Medicine"                                   },
        new Expertise { Code = "560",      Name = "Neuroradiology"                                                  },
        new Expertise { Code = "570",      Name = "Palliative Medicine"                                             },
        new Expertise { Code = "580",      Name = "Pediatric Radiology"                                             },
        new Expertise { Code = "582",      Name = "Pediatric Emergency Medicine"                                    },
        new Expertise { Code = "584",      Name = "Developmental Pediatrics"                                        },
        new Expertise { Code = "474",      Name = "Rheumatology(Int.Med or Ped.)"                                   },
        new Expertise { Code = "900",      Name = "Pediatric Gastroenterology"                                      },
        new Expertise { Code = "905",      Name = "Pediatric Nephrology"                                            },
        new Expertise { Code = "910",      Name = "Pediatric Neurology"                                             },
        new Expertise { Code = "915",      Name = "Pediatric Cardiovascular Surgery"                                },
        new Expertise { Code = "A110",     Name = "Administrative Medicine"                                         },
        new Expertise { Code = "A115",     Name = "Adolescent Medicine"                                             },
        new Expertise { Code = "A120",     Name = "Allergy"                                                         },
        new Expertise { Code = "A130",     Name = "Aviation Medicine"                                               },
        new Expertise { Code = "A135",     Name = "Behavioral Therapy"                                              },
        new Expertise { Code = "A140",     Name = "Child Health"                                                    },
        new Expertise { Code = "A145",     Name = "Cytopathology"                                                   },
        new Expertise { Code = "A155",     Name = "Epidemiology"                                                    },
        new Expertise { Code = "A160",     Name = "Family Medicine"                                                 },
        new Expertise { Code = "315",      Name = "General Surgery"                                                 },
        new Expertise { Code = "319",      Name = "Gynecology"                                                      },
        new Expertise { Code = "320",      Name = "Obstetrics"                                                      },
        new Expertise { Code = "325",      Name = "Medical Scientist(Surgery)"                                      },
        new Expertise { Code = "329",      Name = "Neurosurgery"                                                    },
        new Expertise { Code = "331",      Name = "No Specialty(Surgery)"                                           },
        new Expertise { Code = "336",      Name = "Obstetrics and Gynecology"                                       },
        new Expertise { Code = "338",      Name = "Ophthalmology"                                                   },
        new Expertise { Code = "340",      Name = "Orthopedic Surgery"                                              },
        new Expertise { Code = "342",      Name = "Otolaryngology"                                                  },
        new Expertise { Code = "345",      Name = "Plastic Surgery"                                                 },
        new Expertise { Code = "348",      Name = "Principles of Surgery"                                           },
        new Expertise { Code = "354",      Name = "Thoracic Surgery"                                                },
        new Expertise { Code = "355",      Name = "Thoracic Surgery"                                                },
        new Expertise { Code = "356",      Name = "Cardiac Surgery"                                                 },
        new Expertise { Code = "360",      Name = "Urology"                                                         },
        new Expertise { Code = "405",      Name = "Cardiology(Int.Med.or Ped.)"                                     },
        new Expertise { Code = "409",      Name = "Clinical Imm. Allergy(Int.Med.or Ped.)"                          },
        new Expertise { Code = "305",      Name = "Cardiovascular and Thoracic Surgery"                             },
        new Expertise { Code = "411",      Name = "Critical Care Medicine"                                          },
        new Expertise { Code = "415",      Name = "Endocrin.Metabolism(Int.Med.or Ped.)"                            },
        new Expertise { Code = "417",      Name = "Forensic Pathology(Anatomical/ General)"                         },
        new Expertise { Code = "420",      Name = "Gastroenterology(Int.Med.or Ped.)"                               },
        new Expertise { Code = "425",      Name = "Geriatric Medicine(Int.Med.)"                                    },
        new Expertise { Code = "430",      Name = "Hematology(Int.Med or Ped.)"                                     },
        new Expertise { Code = "431",      Name = "Pediatric Hemat./ Onc. (Pediatrics)"                             },
        new Expertise { Code = "432",      Name = "Neuropathology"                                                  },
        new Expertise { Code = "435",      Name = "Infectious Diseases(Int.Med or Ped.)"                            },
        new Expertise { Code = "452",      Name = "Medical Oncology(Int.Med.)"                                      },
        new Expertise { Code = "460",      Name = "Nephrology(Int.Med or Ped.)"                                     },
        new Expertise { Code = "465",      Name = "Pediatric General Surgery"                                       },
        new Expertise { Code = "472",      Name = "Respirology(Int.Med.or Ped.)"                                    },
        new Expertise { Code = "118",      Name = "Diagnostic and Therapeutic Radiology"                            },
        new Expertise { Code = "122",      Name = "Emergency Medicine"                                              },
        new Expertise { Code = "126",      Name = "Gastroenterology"                                                },
        new Expertise { Code = "130",      Name = "Hematology"                                                      },
        new Expertise { Code = "136",      Name = "Internal Medicine"                                               },
        new Expertise { Code = "140",      Name = "Medical Scientist(Medicine)"                                     },
        new Expertise { Code = "145",      Name = "Neurology"                                                       },
        new Expertise { Code = "146",      Name = "Neurology and/ or Psychiatry"                                    },
        new Expertise { Code = "149",      Name = "No Specialty(Medicine)"                                          },
        new Expertise { Code = "150",      Name = "Medical Genetics"                                                },
        new Expertise { Code = "151",      Name = "Nuclear Medicine"                                                },
        new Expertise { Code = "152",      Name = "Urological Oncology"                                             },
        new Expertise { Code = "153",      Name = "Paediatric Oncology"                                             },
        new Expertise { Code = "154",      Name = "Community Oncology"                                              },
        new Expertise { Code = "155",      Name = "Occupational Medicine"                                           },
        new Expertise { Code = "159",      Name = "Pediatric Cardiology"                                            },
        new Expertise { Code = "160",      Name = "Pediatrics"                                                      },
        new Expertise { Code = "162",      Name = "Physical Medicine Rehabilitation"                                },
        new Expertise { Code = "165",      Name = "Psychiatry"                                                      },
        new Expertise { Code = "168",      Name = "Public Health"                                                   },
        new Expertise { Code = "172",      Name = "Radiation Oncology"                                              },
        new Expertise { Code = "176",      Name = "Respirology"                                                     },
        new Expertise { Code = "180",      Name = "Rheumatology"                                                    },
        new Expertise { Code = "190",      Name = "Therapeutic Radiology"                                           },
        new Expertise { Code = "202",      Name = "Anatomical Pathology"                                            },
        new Expertise { Code = "210",      Name = "General Pathology"                                               },
        new Expertise { Code = "215",      Name = "Hematological Pathology"                                         },
        new Expertise { Code = "225",      Name = "Medical Biochemistry"                                            },
        new Expertise { Code = "227",      Name = "Medical Microbiology"                                            },
        new Expertise { Code = "232",      Name = "Neuropathology"                                                  },
        new Expertise { Code = "240",      Name = "Pathology and Bacteriology"                                      },
        new Expertise { Code = "302",      Name = "Cardiothoracic Surgery"                                          },
        new Expertise { Code = "15 ",      Name = "Malignant Disease Specialist"                                    },
        new Expertise { Code = "101",      Name = "Anaesthesia"                                                     },
        new Expertise { Code = "105",      Name = "Cardiology"                                                      },
        new Expertise { Code = "107",      Name = "Clinical Immunology"                                             },
        new Expertise { Code = "108",      Name = "Clinical Immunology and Allergy"                                 },
        new Expertise { Code = "110",      Name = "Community Medicine"                                              },
        new Expertise { Code = "115",      Name = "Dermatology"                                                     },
        new Expertise { Code = "117",      Name = "Diagnostic Radiology"                                            },
        new Expertise { Code = "SMD77",    Name = "Pediatric Rheumatology"                                          },
        new Expertise { Code = "SMD78",    Name = "Perinatology"                                                    },
        new Expertise { Code = "SMD79",    Name = "Phlebology"                                                      },
        new Expertise { Code = "SMD8",     Name = "Breastfeeding"                                                   },
        new Expertise { Code = "SMD80",    Name = "Phlebology / Sclerotherapy"                                      },
        new Expertise { Code = "SMD81",    Name = "Psychiatry"                                                      },
        new Expertise { Code = "SMD82",    Name = "Psychological Disorders"                                         },
        new Expertise { Code = "SMD83",    Name = "Psychotherapy"                                                   },
        new Expertise { Code = "SMD84",    Name = "Psychotherapy / Hypnotherapy"                                    },
        new Expertise { Code = "SMD85",    Name = "Psychotherapy: Indiv.Fam. & Marital"                             },
        new Expertise { Code = "SMD86",    Name = "Reproductive Endocrinology"                                      },
        new Expertise { Code = "SMD87",    Name = "Sclerotherapy of Varicose Veins"                                 },
        new Expertise { Code = "SMD88",    Name = "Shoulder Surgery"                                                },
        new Expertise { Code = "SMD89",    Name = "Sleep Disorders Medicine"                                        },
        new Expertise { Code = "SMD9",     Name = "Cardiac Rhythm Disturbances Pacemaker"                           },
        new Expertise { Code = "SMD90",    Name = "Sport Medicine"                                                  },
        new Expertise { Code = "SMD91",    Name = "Travel Medicine"                                                 },
        new Expertise { Code = "SMD92",    Name = "Treatment of Stress Disorders"                                   },
        new Expertise { Code = "SMD93",    Name = "Uro - oncology"                                                  },
        new Expertise { Code = "SMD94",    Name = "Urogynecology"                                                   },
        new Expertise { Code = "SMD95",    Name = "Non-Spine Musculoskeletal Conditions"                            },
        new Expertise { Code = "SMD96",    Name = "Burn Surgery"                                                    },
        new Expertise { Code = "SMD97",    Name = "Speech and Hearing Disorders"                                    },
        new Expertise { Code = "SMD98",    Name = "Oncological Surgery Liver and Pancreas"                          },
        new Expertise { Code = "SMD99",    Name = "Child and Maternal Health"                                       },
        new Expertise { Code = "SMD5",     Name = "Arthro.And Reconstruct. Joint Surgery"                           },
        new Expertise { Code = "SMD50",    Name = "Knee Surgery"                                                    },
        new Expertise { Code = "SMD51",    Name = "Laparoscopic General Surgery"                                    },
        new Expertise { Code = "SMD52",    Name = "Laser Surgery"                                                   },
        new Expertise { Code = "SMD53",    Name = "Mammography"                                                     },
        new Expertise { Code = "SMD54",    Name = "Maternity Care & Diseases of Females"                            },
        new Expertise { Code = "SMD55",    Name = "Medical Genetics"                                                },
        new Expertise { Code = "SMD56",    Name = "Neonatology"                                                     },
        new Expertise { Code = "SMD57",    Name = "Neuro - ophthalmology"                                           },
        new Expertise { Code = "SMD58",    Name = "Neuro-otology"                                                   },
        new Expertise { Code = "SMD59",    Name = "Neuroanesthesia"                                                 },
        new Expertise { Code = "SMD6",     Name = "Arthro. And Recon. Surg. (Knee / Shoulder)"                      },
        new Expertise { Code = "SMD60",    Name = "Nutrition"                                                       },
        new Expertise { Code = "SMD61",    Name = "Obstetrics &Gynecology"                                          },
        new Expertise { Code = "SMD62",    Name = "Occupation Related Medical Disorders"                            },
        new Expertise { Code = "SMD63",    Name = "Occupational & Aviation Medicine"                                },
        new Expertise { Code = "SMD64",    Name = "Occupational Health"                                             },
        new Expertise { Code = "SMD65",    Name = "Occupational Medicine"                                           },
        new Expertise { Code = "SMD49",    Name = "Knee & Leg Surgery"                                              },
        new Expertise { Code = "SMD66",    Name = "Occupational Ortho. Clinical Impairment"                         },
        new Expertise { Code = "SMD67",    Name = "Oculo-Plastics"                                                  },
        new Expertise { Code = "SMD68",    Name = "Ophthalmology"                                                   },
        new Expertise { Code = "SMD69",    Name = "OrthopedicSports Medicine in Children"                           },
        new Expertise { Code = "SMD7",     Name = "Aviation Medicine"                                               },
        new Expertise { Code = "SMD70",    Name = "Orthopedic Traumatology"                                         },
        new Expertise { Code = "SMD71",    Name = "Pain Management"                                                 },
        new Expertise { Code = "SMD72",    Name = "Pediatric &Adolescent Gynecology"                                },
        new Expertise { Code = "SMD73",    Name = "Pediatric Ophthamology Adult Strabismus"                         },
        new Expertise { Code = "SMD74",    Name = "Pediatric Orthopedic Surgery"                                    },
        new Expertise { Code = "SMD75",    Name = "Pediatric Orthopedics"                                           },
        new Expertise { Code = "SMD76",    Name = "Pediatric Otolaryngology"                                        },
        new Expertise { Code = "SMD21",    Name = "Diabetes"                                                        },
        new Expertise { Code = "SMD22",    Name = "Diseases of Children"                                            },
        new Expertise { Code = "SMD23",    Name = "Diseases of the Colon and Rectum"                                },
        new Expertise { Code = "SMD24",    Name = "Diseases of the Eye"                                             },
        new Expertise { Code = "SMD25",    Name = "Diseases of the Joints"                                          },
        new Expertise { Code = "SMD26",    Name = "Diseases of the Kidney"                                          },
        new Expertise { Code = "SMD27",    Name = "Resp. Tract Diseases -Children"                                  },
        new Expertise { Code = "SMD28",    Name = "Echocardiography"                                                },
        new Expertise { Code = "SMD29",    Name = "Emergency Care"                                                  },
        new Expertise { Code = "SMD3",     Name = "Allergies"                                                       },
        new Expertise { Code = "SMD30",    Name = "Endocrinology"                                                   },
        new Expertise { Code = "SMD31",    Name = "Endoscopic General Surgery"                                      },
        new Expertise { Code = "SMD32",    Name = "Exercise Medicine"                                               },
        new Expertise { Code = "SMD33",    Name = "Family Therapy"                                                  },
        new Expertise { Code = "SMD34",    Name = "Female Incontinence & Urodynamics"                               },
        new Expertise { Code = "SMD35",    Name = "Forensic Pathology"                                              },
        new Expertise { Code = "SMD36",    Name = "Forensic Psychiatry"                                             },
        new Expertise { Code = "SMD37",    Name = "Forensic Psychiatry Medico-legal Med."                           },
        new Expertise { Code = "SMD38",    Name = "Gastrointestinal Surgery"                                        },
        new Expertise { Code = "SMD20",    Name = "Dermatopathology"                                                },
        new Expertise { Code = "SMD39",    Name = "Geriatric Medicine"                                              },
        new Expertise { Code = "SMD4",     Name = "Allergies -Upper Respiratory Tract"                              },
        new Expertise { Code = "SMD40",    Name = "Geriatric Psychiatry"                                            },
        new Expertise { Code = "SMD41",    Name = "Geriatrics"                                                      },
        new Expertise { Code = "SMD42",    Name = "Geriatrics & Psychotherapy"                                      },
        new Expertise { Code = "SMD43",    Name = "Glaucoma"                                                        },
        new Expertise { Code = "SMD44",    Name = "Hair Restoration Surgery"                                        },
        new Expertise { Code = "SMD45",    Name = "Hand &Wrist Surgery"                                             },
        new Expertise { Code = "SMD46",    Name = "Head and Neck Oncology"                                          },
        new Expertise { Code = "SMD47",    Name = "Hypnotherapy"                                                    },
        new Expertise { Code = "SMD48",    Name = "Joint Replacement & Reconstruction"                              },
        new Expertise { Code = "LPNORTHO", Name = "Orthopaedic"                                                     },
        new Expertise { Code = "402",      Name = "Adolescent Medicine"                                             },
        new Expertise { Code = "410",      Name = "Clinical Pharmacology"                                           },
        new Expertise { Code = "412",      Name = "Colorectal Surgery"                                              },
        new Expertise { Code = "414",      Name = "Developmental Pediatrics"                                        },
        new Expertise { Code = "423",      Name = "General Surgical Oncology"                                       },
        new Expertise { Code = "427",      Name = "Gynecologic Oncology"                                            },
        new Expertise { Code = "428",      Name = "Gynecologic Reproductive Endocrinology and Infertility"          },
        new Expertise { Code = "434",      Name = "Neuroradiology"                                                  },
        new Expertise { Code = "445",      Name = "Maternal - Fetal Medicine"                                       },
        new Expertise { Code = "455",      Name = "Neonatal - Perinatal Medicine"                                   },
        new Expertise { Code = "461",      Name = "Occupational Medicine"                                           },
        new Expertise { Code = "462",      Name = "Pediatric Emergency Medicine"                                    },
        new Expertise { Code = "468",      Name = "Pediatric Radiology"                                             },
        new Expertise { Code = "485",      Name = "Transfusion Medicine"                                            },
        new Expertise { Code = "406",      Name = "Child and Adolescent Psychiatry"                                 },
        new Expertise { Code = "418",      Name = "Forensic Psychiatry"                                             },
        new Expertise { Code = "426",      Name = "Geriatric Psychiatry"                                            },
        new Expertise { Code = "470",      Name = "Pain Medicine"                                                   },
        new Expertise { Code = "421",      Name = "General Internal Medicine"                                       }
    };
}
