apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
  - name: git-repository-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.pull_request.head.sha)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-short-sha
    value: $(extensions.truncated_sha)
  - name: git-pr-number
    value: pr-$(extensions.pr_number)
  - name: git-branch-name
    value: $(extensions.branch_name)