apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pr
  namespace: f088b1-tools
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
            - name: ""
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 250m
                  memory: 64Mi
            serviceAccountName: pipeline
  serviceAccountName: ""
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: github-pr-binding
    name: github-pr-trigger
    interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'pull_request') &&
          body.action in ['opened', 'reopened', 'synchronize']) &&
          body.pull_request.head.repo.full_name == 'bcgov/moh-pidp'
        overlays:
        - key: truncated_sha
          expression: "body.pull_request.head.sha.truncate(7)"
        - key: pr_number
          expression: "body.number"
        - key: branch_name
          expression: "body.pull_request.head.ref.replace('/', '_')"
    template:
      ref: github-pr-trigger-template
  - bindings:
    - kind: TriggerBinding
      ref: github-pr-binding
    name: pr-cleanup-trigger
    interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'pull_request') &&
          body.action in ['closed', 'deleted']) &&
          body.pull_request.head.repo.full_name == 'bcgov/moh-pidp'
        overlays:
        - key: pr_number
          expression: "body.number"
    template:
      ref: pr-cleanup-trigger-template