apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
- cronjobs.yaml
- networkpolicy.yaml
- pvc.yaml
- rbac.yaml
- secret.yaml
- services.yaml
- statefulsets.yaml
images:
- name: patroni-postgres
  newName: image-registry.openshift-image-registry.svc:5000/bcgov/patroni-postgres:12.4-latest
- name: openshift-cli-image
  newName: image-registry.openshift-image-registry.svc:5000/openshift/cli  
resources:
- ../../base
- transportserverclaim.yaml