apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firely-server.fullname" . }}-conf
  labels:
    {{- include "firely-server.labels" . | nindent 4 }}
data:
  VONK_License__LicenseFile : {{ .Values.license.mountPath }}/{{ .Values.license.fileName }}
{{- if .Values.license.requestInfoFile }}
  VONK_License__RequestInfoFile : {{ .Values.license.requestInfoFile }}
{{- end }}
{{- if .Values.license.writeRequestInfoFileInterval }}
  VONK_License__WriteRequestInfoFileInterval : {{ .Values.license.writeRequestInfoFileInterval | quote }}
{{- end }}