{{- if .Values.license.value }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "firely-server.name" . }}
    helm.sh/chart: {{ include "firely-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "firely-server.fullname" . }}-license-secret
type: Opaque
data:
  {{ .Values.license.fileName }}: {{ .Values.license.value | b64enc }}
{{- end -}}