apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firely-server.fullname" . }}-settings-json
  labels:
    {{- include "firely-server.labels" . | nindent 4 }}
data:
  appsettings.json: |- 
  {{ .Values.vonksettings | toJson | indent 2  }}
  logsettings.json: |- 
  {{ .Values.logsettings | toJson | indent 2  }}