{{- if .Values.validation.enabled -}}
{{- $fullName := include "firely-server.fullname" . -}}
{{- $validationName := printf "%s-validation" $fullName -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $validationName }}
  labels:
    {{- include "firely-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.validation.replicaCount }}
  selector:
    matchLabels:
      {{- include "firely-server-validation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "firely-server-validation.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/validation-settings.configmap: {{ include (print $.Template.BasePath "/validation-settings-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: validation
          image: "{{ .Values.validation.image.registry }}/{{ .Values.validation.image.repository }}:{{ .Values.validation.image.tag }}"
          imagePullPolicy: {{ .Values.validation.image.pullPolicy }}
          volumeMounts:
          - name: validation-settings
            mountPath: /app/appsettings.json
            subPath: appsettings.json
          - name: carfiles-storage
            mountPath: /var/run/carfiles
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.validation.resources | nindent 12 }}
      volumes:
      - name: validation-settings
        configMap:
          name: {{ include "firely-server.fullname" . }}-validation-settings-json
      - name: carfiles-storage
      {{- if .Values.validation.persistence.carfilePVClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.validation.persistence.carfilePVClaim }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.validation.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.validation.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.validation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}