{{- if .Values.validation.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firely-server.fullname" . }}-validation-settings-json
  labels:
    {{- include "firely-server.labels" . | nindent 4 }}
data:
  appsettings.json: |- 
  {{ .Values.validationsettings | toJson | indent 2  }}
{{- end }}