{{- if .Values.validation.enabled }}
{{- $fullName := include "firely-server.fullname" . -}}
{{- $validationName := printf "%s-validation" $fullName -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $validationName }}
  labels:
    {{- include "firely-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.validation.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "firely-server-validation.selectorLabels" . | nindent 4 }}
{{- end }}