# This job runs on GoldDR only and is designed to probe GoldDR's version of Patroni and determine if it's running.
# If it's not running then we'll promote Gold's patroni to be leader.

kind: CronJob
apiVersion: batch/v1
metadata:
  name: patroni-probe
  labels:
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
    app: patroni
    cluster-name: patroni
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: patroni-trigger
              image: openshift-cli-image
              args:
                - /bin/sh
                - '-c'
                - '/failover.sh'
              volumeMounts:
                - name: patroni-intercom
                  mountPath: /intercom
                - name: patroni-failover
                  mountPath: /failover.sh
                  subPath: failover.sh

          initContainers:
            - name: patroni-initprobe
              # This container obtains the TS port that we use to connect to GoldDR in the probe container to follow
              image: openshift-cli-image
              args:
                - /bin/sh
                - '-c'
                - '/gettsport.sh'
              volumeMounts:
                - name: patroni-intercom
                  mountPath: /intercom
                - name: patroni-gettsport
                  mountPath: /gettsport.sh
                  subPath: gettsport.sh
            - name: patroni-probe
              # This container will attempt a connection to the PSQL on GoldDR through the TS service
              image: patroni-postgres
              args:
                - /bin/sh
                - '-c'
                - '/probe.sh'
              volumeMounts:
                - name: patroni-intercom
                  mountPath: /intercom
                - name: patroni-probe
                  mountPath: /probe.sh
                  subPath: probe.sh

          volumes:
            # This is a empty folder used to allow for communications between containers in the same pod.
            - name: patroni-intercom
              emptyDir: {}
            - name: patroni-probe
              configMap:
                name: patroni-probe
                defaultMode: 0555
            - name: patroni-failover
              configMap:
                name: patroni-failover
                defaultMode: 0555
            - name: patroni-gettsport
              configMap:
                name: patroni-gettsport
                defaultMode: 0555

          serviceAccount: patroni
          restartPolicy: OnFailure