kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-patroni-0
  labels:
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
    app: patroni
    cluster-name: patroni
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem