# Create a service account and appropriate rules/rule bindings for our patroni implementation.
---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
    app: patroni
    cluster-name: licenseplate
  name: patroni
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
    app: patroni
    cluster-name: patroni
  name: patroni
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/instance: patroni
    app.kubernetes.io/name: patroni
    app.kubernetes.io/component: database
    app: patroni
    cluster-name: patroni
  name: patroni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patroni
subjects:
  - kind: ServiceAccount
    name: patroni