{{- if .Values.migrations.enabled }}
{{ $release := .Release.Name }}
{{ $ocEnv := regexFind "([^-]*$)" .Release.Namespace }}
{{ $isPR := hasPrefix "pr-" .Release.Name }}
## Derived release name
{{ $drn := ternary $release $ocEnv $isPR }}
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "plr-intake.fullname" . }}-migrations
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "10"
  labels:
    {{- include "plr-intake.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.global.image.registry }}/{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        command: ['./efbundle', '--connection', '$(ConnectionStrings__PlrDatabase)']
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: database-host
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ ternary $ocEnv $release $isPR }}-patroni-secret
                key: app-db-password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ ternary $ocEnv $release $isPR }}-patroni-secret
                key: app-db-username
          - name: POSTGRESQL_DATABASE
            {{- if $isPR }}
            value: pidp_{{ $drn }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: {{ ternary $ocEnv $release $isPR }}-patroni-secret
                key: app-db-name
            {{- end }}
          - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
            value: /tmp
          - name: ConnectionStrings__PlrDatabase
            value: "Host=$(DB_HOST);Port=5432;Database=$(POSTGRESQL_DATABASE);Username=$(POSTGRESQL_USER);Password=$(POSTGRESQL_PASSWORD)"
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
