- apiVersion: v1
  kind: Secret
  stringData:
    username: {{ .Values.auth.username }}
    password: {{ .Values.auth.password }}
    url: "amqp://{{ .Values.auth.username }}:{{ .Values.auth.password }}@${CLUSTER_NAME}-balancer"
    cookie: {{ .Values.auth.erlangCookie }}
  metadata:
    name: ${CLUSTER_NAME}-secret
  type: Opaque

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${CLUSTER_NAME}-config
  data:
    rabbitmq.conf: |
     loopback_users.guest = false

     ## Clustering
     cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
     cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
     cluster_formation.k8s.address_type = hostname
     cluster_formation.k8s.hostname_suffix = .rabbitmq-cluster.dfb30e-test.svc.cluster.local
     cluster_formation.node_cleanup.interval = 10
     cluster_formation.node_cleanup.only_log_warning = true
     cluster_partition_handling = autoheal
     ## queue master locator
     queue_master_locator=min-masters