# This service account is needed for rabbit_peer_discovery_k8s plugin to be able to discover
# cluster nodes
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: {{ .Values.serviceAccount.name }}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: {{ .Values.serviceAccount.name }}-view
  roleRef:
    kind: Role
    name: view
  subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}