kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rabbitmq-load-definition
type: Opaque
stringData:
  load_definition.json: |-
    {
        "permissions": [
            {
                "configure": ".*",
                "read": ".*",
                "user": "pidp",
                "vhost": "/",
                "write": ".*"
            },
            {
                "configure": ".*",
                "read": ".*",
                "user": "rabbitmq",
                "vhost": "/",
                "write": ".*"
            }
        ],
        "users": [
            {
                "hashing_algorithm": "rabbit_password_hashing_sha256",
                "limits": {},
                "name": "rabbitmq",
                "password_hash": "EdW43QN/0JrFle4tED3scSejEKVKScVowH/VNhglxI0LFaq5",
                "tags": [
                    "administrator"
                ]
            },
            {
                "hashing_algorithm": "rabbit_password_hashing_sha256",
                "limits": {},
                "name": "pidp",
                "password_hash": "7R4NIi/1BT3Zk0C6dLsaD3igb+0Q02ZGo4BmqPT1jcFABCn5",
                "tags": []
            }
        ]
    }