name: Build Midas Probe

on:
  push:
    branches:
      - 'develop'
    paths: [midas-probe/openshift]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment:"
        type: choice
        default: 'dev'
        required: true
        options:
          - dev
          - test

jobs:
  build:
    name: Build Midas Probe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image with docker-compose
        working-directory: midas-probe
        run: |
          docker-compose build midas-probe

      - name: Docker Login to ImageStream 
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: Tag and Push Docker image
        run: |
          docker tag midas-probe image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/midas-probe:${{ github.event.inputs.Environment }}
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/midas-probe --all-tags
      
      - name: OC Login to Silver OCP
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_PIPELINE_SERVICE_ACCOUNT_TOKEN}}

      - name: helm deployment
        working-directory: midas-probe/openshift/helm
        run: |
          echo installing midas-common helm chart...
          helm upgrade --install --values ./midas-common/values.yaml --set namespace=d8a8f9-${{ github.event.inputs.Environment }} --namespace d8a8f9-${{ github.event.inputs.Environment }} midas-common midas-common
          echo installing midas-probe helm chart...
          helm upgrade --install --values ./midas-probe/values.yaml --set imageStreamTag=${{ github.event.inputs.Environment }} --namespace d8a8f9-${{ github.event.inputs.Environment }} midas-probe midas-probe
