name: Build Frontend

on:
  push:
    branches: [workflows]
    paths:
      - "workspace/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    name: Frontend Build and Deploy
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: "Build Frontend"
        working-directory: "./workspace"
        run: |
          npm install
          npm build
          docker build -t image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-frontend:chris .

      # Uses the builder service account token
      - name: "Docker Login to Silver OCP"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-frontend:chris
