name: Build PLR-Intake Backend - Dev

on:
  push:
    branches: [develop]
    paths:
      - "backend/services.plr-intake/**"
      - "backend/services.plr-intake.tests/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-plr-intake-silver:
    name: PLR Intake Backend Build - Silver
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend/services.plr-intake"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: "Docker Build"
        run: |
          docker build -t pidp-plr-intake:develop .
          docker tag pidp-plr-intake:develop image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-plr-intake:develop

      # Uses the builder service account token
      - name: "Docker Login to Silver OCP"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-plr-intake:develop

  build-plr-intake-gold:
    name: PLR Intake Backend Build - Gold
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend/services.plr-intake"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master


      #  Uses the builder service account token
      - name: "Docker Login to GOLD OCP"
        uses: docker/login-action@master
        with:
          registry: image-registry.apps.gold.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.GOLD_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker tag pidp-plr-intake:develop image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop
          docker push image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop

      - name: "Docker Build GOLDDR image"
        run: |
          docker tag image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop image-registry.apps.golddr.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop

      #  Uses the builder service account token
      - name: "Docker Login to GOLDDR OCP"
        uses: docker/login-action@master
        with:
          registry: image-registry.apps.golddr.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.GOLDDR_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker tag pidp-plr-intake:develop image-registry.apps.golddr.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop
          docker push image-registry.apps.golddr.devops.gov.bc.ca/f088b1-tools/pidp-plr-intake:develop