name: Build WebAPI

on:
  push:
    branches: [develop]
    paths:
      - "backend/webapi/**"
      - "backend/webapi.tests/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-webapi:
    name: WebAPI Backend Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend/webapi"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: "Docker Build"
        run: |
          docker build -t image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-webapi:dev .

      # Uses the builder service account token
      - name: "Docker Login to Silver OCP"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-webapi:dev
  
  helm-deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'web-api'
        namespace: 'd8a8f9-dev'
        chart: 'charts/pidp/web-api**'
        value-files: "deploy/dev_values.yaml"