name: Build Frontend - Dev

on:
  pull_request:
  push:
    branches: [develop]
    paths:
      - "workspace/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-frontend:
    name: Frontend Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./workspace"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: YARN Install
        run: |
          yarn install

      - name: YARN Build
        run: |
          yarn build

      - name: "Docker Build"
        run: |
          docker build -t image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-frontend:dev .

      # Uses the builder service account token
      - name: "Docker Login to Silver OCP"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-frontend:dev

  helm-deployment:
    needs: [build-and-deploy-frontend]
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'frontend'
        namespace: 'd8a8f9-dev'
        chart: 'charts/pidp/frontend**'
        # token: '${{ github.token }}'
        # values: |
        #   name: foobar
        value-files: "deploy/dev_values.yaml"

  #     env:
  #       KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'