name: Build Endorsement Reminder - GOLD Dev

on:
  push:
    branches: [develop]
    paths:
     - "backend/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-endorsement-reminder-gold:
    name: Endorsement Reminder Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: "Docker Build"
        working-directory: "./backend"
        run: |
          docker build -f ./services.endorsement-reminder/Dockerfile -t image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/endorsement-reminder:develop .

      # Uses the Artifactory service account's username and password
      - name: "Docker Login to GOLD OCP"
        uses: docker/login-action@master
        with:
          registry: image-registry.apps.gold.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.GOLD_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/endorsement-reminder:develop