name: Deploy Helm Charts - GOLD Dev

on:
  push:
    branches: [develop]
    paths:
      - "charts/**"
      - "./deploy/dev_values.yaml"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  helm-deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{secrets.GOLD_OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_PIPELINE_SERVICE_ACCOUNT_TOKEN}}
          namespace: ${{secrets.GOLD_LICENSE_PLATE}}-dev

      - name: Helm Deploy / install command
        run: |
          echo current installed helm releases
          helm list --namespace f088b1-dev

          echo installing helm chart...
          helm upgrade --wait --values ./deploy/dev_values.yaml --namespace f088b1-dev dev charts/pidp --debug
