name: dev-build-tools-do-work

on:
  push:
    branches: [develop, fix/imms2-uat4]
    paths:
      - "backend/tools.do-work/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-deploy-tools-do-work:
    name: Tools Do Work Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089

      - name: "Docker Build GOLD"
        working-directory: "./backend"
        run: |
          docker build -f ./tools.do-work/Dockerfile -t image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/tools-do-work:develop .

      # Uses the builder service account token
      - name: "Docker Login to GOLD OCP"
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: image-registry.apps.gold.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.GOLD_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/tools-do-work:develop

      - name: "Docker Build GOLDDR"
        working-directory: "./backend"
        run: |
          docker tag image-registry.apps.gold.devops.gov.bc.ca/f088b1-tools/tools-do-work:develop image-registry.apps.golddr.devops.gov.bc.ca/f088b1-tools/tools-do-work:develop

      # Uses the builder service account token
      - name: "Docker Login to GOLDDR OCP"
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: image-registry.apps.golddr.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.GOLDDR_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.golddr.devops.gov.bc.ca/f088b1-tools/tools-do-work:develop



