name: Deploy DB Migration - Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  db-migration-gold:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master

      - name: Install CLI tools from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          # Search through these projects' GitHub releases, instead of the OpenShift Mirror.
          # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
          source: "github"
          # Using GitHub token from the github context
          github_pat: ${{ secrets.GITHUB_TOKEN }}   
          oc: "4"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{secrets.GOLD_OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN}}

      - name: deply db migration job - Gold
        run: |
          oc project f088b1-prod

          echo deleting prod-webapi-migrations job
          oc delete job/prod-webapi-migrations -n f088b1-prod --ignore-not-found

          echo applying web-api-migration template...
          helm template prod charts/webapi -n f088b1-prod --values ./deploy/prod_values.yaml -s templates/migrations.yaml --wait --debug | oc apply -n f088b1-prod -f -

          echo deleting prod-plr-intake-migrations job
          oc delete job/prod-plr-intake-migrations -n f088b1-prod --ignore-not-found

          echo applying plr-intake-migration template...
          helm template prod charts/plr-intake -n f088b1-prod --values ./deploy/prod_values.yaml -s templates/migrations.yaml --wait --debug | oc apply -n f088b1-prod -f -
