name: Deploy Test Helm Charts - Endorsement Reminder

on:
  push:
    branches: [main]
    paths:
      - "infra/endorsement_reminder/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-deployment-endorsement-reminder-gold:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master

      - name: Install CLI tools from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{secrets.GOLD_OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN}}

      - name: Helm Deploy Upgrade
        run: |
          echo current installed helm releases
          helm list --namespace f088b1-test

          echo installing helm chart...
          helm upgrade --wait --namespace f088b1-prod --values infra/endorsement_reminder/values.yaml --set env=prod --set global.image.tag=main --set aspnetcore.environment=Production  endorsement-reminder infra/endorsement_reminder

