name: Deploy Helm Charts - Prod - Gold

on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - "./deploy/prod_values_gold.yaml"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-deployment-gold:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1 
  
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{secrets.GOLD_OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN}}
  
      - name: Helm Deploy / install command
        run: |
          echo current installed helm releases
          helm list --namespace f088b1-prod
  
          echo installing helm chart...
          helm upgrade --wait --values ./deploy/prod_values_gold.yaml --namespace f088b1-prod prod charts/pidp --debug 
