name: Build PLR-Intake Backend

on:
  workflow_dispatch:
  push:
    paths:
      - "backend/services.plr-intake/**"
      - "backend/services.plr-intake.tests/**"
    branches: [workflows]
      # branches-ignore:
    # - 'develop'
    # - 'test'
    # - 'main'
  pull_request:
    paths:
      - "backend/services.plr-intake/**"
      - "backend/services.plr-intake.tests/**"
    branches: [workflows]
      # branches-ignore:
    # - 'develop'
    # - 'test'
    # - 'main'


# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-plr-intake:
    name: PLR Intake Backend Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend/services.plr-intake"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@master

      - name: "Docker Build"
        run: |
          docker build -t image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-plr-intake:pr-${{ github.event.number }} .

      # Uses the builder service account token
      - name: "Docker Login to Silver OCP"
        uses: docker/login-action@v2
        with:
          registry: image-registry.apps.silver.devops.gov.bc.ca
          username: builder
          password: ${{ secrets.SILVER_TOOLS_BUILDER_TOKEN }}

      - name: "Push image"
        run: |
          docker push image-registry.apps.silver.devops.gov.bc.ca/d8a8f9-tools/pidp-plr-intake:pr-${{ github.event.number }}
