name: Remove Helm deployment on PR merge
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches-ignore:
      - 'test'
      - 'master'
jobs:
  remove-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1.1
      with:
        openshift_server_url: ${{secrets.OPENSHIFT_CLUSTER_URL}}
        openshift_token: ${{secrets.OPENSHIFT_PIPELINE_SERVICE_ACCOUNT_TOKEN}}

    - name: Get Pull Request Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove Helm deployment
      run: |
        helm uninstall pr-${{ steps.pr.outputs.pull_request_number }} --namespace d8a8f9-dev

    - name: Remove PR imagestream
      run: |
        oc tag -d pidp-frontend:pr-${{ steps.pr.outputs.pull_request_number }} -n d8a8f9-tools
        oc tag -d pidp-plr-intake:pr-${{ steps.pr.outputs.pull_request_number }} -n d8a8f9-tools
        oc tag -d pidp-pidp-webapi:pr-${{ steps.pr.outputs.pull_request_number }} -n d8a8f9-tools

  merge_job:
      # this job will only run if the PR has been merged
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo PR #${{ steps.pr.outputs.pull_request_number }} has been merged

  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ steps.pr.outputs.pull_request_number }} has been closed without being merged