name: Promote Frontend image - test

on:
  push:
    branches: [test]
    paths:
      - "workspace/**"
  workflow_dispatch:

env:
  ORIG_TAG: develop
  PROMOTE_TAG: test

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote-image-to-test-gold:
    name: Frontend Promote to test - Gold
    runs-on: ubuntu-latest
    steps:     
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.9"

      - name: oc login - Gold
        run: |
          oc login --token=${{ secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN }} --server=${{ secrets.GOLD_OPENSHIFT_CLUSTER_URL }}

      - name: Promote frontend from dev to test - Gold
        run: |
          oc -n f088b1-tools tag \
          f088b1-tools/pidp-frontend:${{ env.ORIG_TAG }} \
          f088b1-tools/pidp-frontend:${{ env.PROMOTE_TAG }}

      - name: oc login - Golddr
        run: |
          oc login --token=${{ secrets.GOLDDR_PIPELINE_SERVICE_ACCOUNT_TOKEN }} --server=${{ secrets.GOLDDR_OPENSHIFT_CLUSTER_URL }}

      - name: Promote frontend from dev to test - Golddr
        run: |
          oc -n f088b1-tools tag \
          f088b1-tools/pidp-frontend:${{ env.ORIG_TAG }} \
          f088b1-tools/pidp-frontend:${{ env.PROMOTE_TAG }}
