name: Deploy Test Helm Charts - Tools Do Work

on:
  push:
    branches: [test]
    paths:
      - "infra/tools-do-work/**"
  workflow_dispatch:

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-deployment-tools-do-work-gold:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master

      - name: Install CLI tools from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{secrets.GOLD_OPENSHIFT_CLUSTER_URL}}
          openshift_token: ${{secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN}}

      - name: Helm Deploy Upgrade
        run: |
          echo current installed helm releases
          helm list --namespace f088b1-test

          echo installing helm chart...
          helm upgrade --wait --namespace f088b1-test --values infra/tools-do-work/values.yaml --set global.image.tag=test --set env=test tools-do-work infra/tools-do-work

