name: Promote Endorsement Schedule image - test

on:
  push:
    branches: [test]
    paths:
      - "backend/**"
  workflow_dispatch:

env:
  ORIG_TAG: develop
  PROMOTE_TAG: test

  # This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote-image-to-test-gold:
    name: Promote endorsement-reminder from dev to test
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.9"

      - name: oc login - GOLD
        run: |
          oc login --token=${{ secrets.GOLD_PIPELINE_SERVICE_ACCOUNT_TOKEN }} --server=${{ secrets.GOLD_OPENSHIFT_CLUSTER_URL }}

      - name: Promote endorsement-reminder from dev to test - GOLD
        run: |
          oc -n f088b1-tools tag \
          f088b1-tools/endorsement-reminder:${{ env.ORIG_TAG }} \
          f088b1-tools/endorsement-reminder:${{ env.PROMOTE_TAG }}

      - name: oc login - GOLDDR
        run: |
          oc login --token=${{ secrets.GOLDDR_PIPELINE_SERVICE_ACCOUNT_TOKEN }} --server=${{ secrets.GOLDDR_OPENSHIFT_CLUSTER_URL }}

      - name: Promote endorsement-reminder from dev to test - GOLDDR
        run: |
          oc -n f088b1-tools tag \
          f088b1-tools/endorsement-reminder:${{ env.ORIG_TAG }} \
          f088b1-tools/endorsement-reminder:${{ env.PROMOTE_TAG }}
