name: ZAP Scanner
on:
  workflow_run:
    workflows: ["Build All - PR"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment:"
        type: choice
        required: true
        options:
        - PR
        - DEV

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set environment
        run: |
            if [ ${{ github.event.inputs.Environment }} == 'PR' ]; then
            echo "ZAP_URL=dev.healthprovideridentityportal.gov.bc.ca/auth/login" >> $GITHUB_ENV
            elif [ ${{ github.event.inputs.Environment }} == 'DEV' ]; then
            echo "ZAP_URL=dev.healthprovideridentityportal.gov.bc.ca/auth/login" >> $GITHUB_ENV
            fi

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          issue_title: "ZAP Scan Report"
          fail_action: false
          target: ${{ env.ZAP_URL }}
          cmd_options: '-a'

