name: ZAP Scanner
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: ['develop']


permissions:
    contents: read
    issues: write

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          issue_title: "ZAP Scan Reports"
          fail_action: false
          target: "https://dev.healthprovideridentityportal.gov.bc.ca/auth/login"
          cmd_options: '-a'