name: ZAP Scanner
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment:"
        type: choice
        required: true
        options:
        - PR
        - DEV
  push:
    branches: ['develop','zapscan']

permissions: read-all

# This will terminate builds that are previously, but continuing to run.  Saves GHA hours.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set environment
        run: |
            if [ ${{ github.event.inputs.Environment }} == 'PR' ]; then
            echo "ZAP_URL=https://dev.healthprovideridentityportal.gov.bc.ca/auth/login" >> $GITHUB_ENV
            elif [ ${{ github.event.inputs.Environment }} == 'DEV' ]; then
            echo "ZAP_URL=https://dev.healthprovideridentityportal.gov.bc.ca/auth/login" >> $GITHUB_ENV
            fi

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "owasp/zap2docker-stable"
          issue_title: "ZAP Scan Report"
          fail_action: false
          target: "https://dev.healthprovideridentityportal.gov.bc.ca/auth/login"
          cmd_options: '-a'

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v3
        with:
            name: OWASP ZAP - MSP Direct UAT Front End Report
            path: report_html.html